pipeline {
    agent any
    stages {
        //stage('Clone repository') {
        //  steps {
        //       checkout([$class: 'GitSCM', 
        //     branches: [[name: '*/main']], 
         //       userRemoteConfigs: [[url: 'https://github.com/Mannpreeth/PES1UG22CS816_Jenkins.git']]])
        // }
        //}
        stage('Build') {
            steps {
                sh 'g++ -o PES1UG22CS816-1 main.cpp'
            }
        }
        stage('Test') {
            steps {
                sh './PES1UG22CS816-1'
            }
        }
        stage('Deploy') {
            steps {
                echo 'deploy'
            }
        }
    }
    post {
        failure {
            echo 'Pipeline failed'
        }
    }
}

